package com.pandatech.downloadcf.mapper;

import com.pandatech.downloadcf.entity.EslBrandFieldMapping;
import com.pandatech.downloadcf.entity.EslBrandFieldMappingCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface EslBrandFieldMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    long countByExample(EslBrandFieldMappingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(EslBrandFieldMappingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int insert(EslBrandFieldMapping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int insertSelective(EslBrandFieldMapping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    List<EslBrandFieldMapping> selectByExampleWithBLOBsWithRowbounds(EslBrandFieldMappingCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    List<EslBrandFieldMapping> selectByExampleWithBLOBs(EslBrandFieldMappingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    List<EslBrandFieldMapping> selectByExampleWithRowbounds(EslBrandFieldMappingCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    List<EslBrandFieldMapping> selectByExample(EslBrandFieldMappingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    EslBrandFieldMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") EslBrandFieldMapping row, @Param("example") EslBrandFieldMappingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") EslBrandFieldMapping row, @Param("example") EslBrandFieldMappingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") EslBrandFieldMapping row, @Param("example") EslBrandFieldMappingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EslBrandFieldMapping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EslBrandFieldMapping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EslBrandFieldMapping row);
}