package com.pandatech.downloadcf.mapper;

import com.pandatech.downloadcf.entity.PandaEsl;
import com.pandatech.downloadcf.entity.PandaEslCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PandaEslMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    long countByExample(PandaEslCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int deleteByExample(PandaEslCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int insert(PandaEsl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int insertSelective(PandaEsl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    List<PandaEsl> selectByExampleWithBLOBsWithRowbounds(PandaEslCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    List<PandaEsl> selectByExampleWithBLOBs(PandaEslCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    List<PandaEsl> selectByExampleWithRowbounds(PandaEslCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    List<PandaEsl> selectByExample(PandaEslCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    PandaEsl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PandaEsl row, @Param("example") PandaEslCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") PandaEsl row, @Param("example") PandaEslCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PandaEsl row, @Param("example") PandaEslCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PandaEsl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PandaEsl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PandaEsl row);
}