package com.pandatech.downloadcf.mapper;

import com.pandatech.downloadcf.entity.PandaProduct;
import com.pandatech.downloadcf.entity.PandaProductCriteria;
import com.pandatech.downloadcf.entity.PandaProductWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PandaProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    long countByExample(PandaProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int deleteByExample(PandaProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int insert(PandaProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int insertSelective(PandaProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    List<PandaProductWithBLOBs> selectByExampleWithBLOBsWithRowbounds(PandaProductCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    List<PandaProductWithBLOBs> selectByExampleWithBLOBs(PandaProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    List<PandaProduct> selectByExampleWithRowbounds(PandaProductCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    List<PandaProduct> selectByExample(PandaProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    PandaProductWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PandaProductWithBLOBs row, @Param("example") PandaProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") PandaProductWithBLOBs row, @Param("example") PandaProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PandaProduct row, @Param("example") PandaProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PandaProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PandaProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PandaProduct row);
}