package com.pandatech.downloadcf.mapper;

import com.pandatech.downloadcf.entity.PrintTemplateDesign;
import com.pandatech.downloadcf.entity.PrintTemplateDesignCriteria;
import com.pandatech.downloadcf.entity.PrintTemplateDesignWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PrintTemplateDesignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    long countByExample(PrintTemplateDesignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int deleteByExample(PrintTemplateDesignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int insert(PrintTemplateDesignWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int insertSelective(PrintTemplateDesignWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    List<PrintTemplateDesignWithBLOBs> selectByExampleWithBLOBsWithRowbounds(PrintTemplateDesignCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    List<PrintTemplateDesignWithBLOBs> selectByExampleWithBLOBs(PrintTemplateDesignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    List<PrintTemplateDesign> selectByExampleWithRowbounds(PrintTemplateDesignCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    List<PrintTemplateDesign> selectByExample(PrintTemplateDesignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    PrintTemplateDesignWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PrintTemplateDesignWithBLOBs row, @Param("example") PrintTemplateDesignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") PrintTemplateDesignWithBLOBs row, @Param("example") PrintTemplateDesignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PrintTemplateDesign row, @Param("example") PrintTemplateDesignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PrintTemplateDesignWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PrintTemplateDesignWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_template_design
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PrintTemplateDesign row);
}