package com.pandatech.downloadcf.mapper;

import com.pandatech.downloadcf.entity.ProductEslBinding;
import com.pandatech.downloadcf.entity.ProductEslBindingCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ProductEslBindingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    long countByExample(ProductEslBindingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int deleteByExample(ProductEslBindingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int insert(ProductEslBinding row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int insertSelective(ProductEslBinding row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    List<ProductEslBinding> selectByExampleWithBLOBsWithRowbounds(ProductEslBindingCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    List<ProductEslBinding> selectByExampleWithBLOBs(ProductEslBindingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    List<ProductEslBinding> selectByExampleWithRowbounds(ProductEslBindingCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    List<ProductEslBinding> selectByExample(ProductEslBindingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    ProductEslBinding selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ProductEslBinding row, @Param("example") ProductEslBindingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") ProductEslBinding row, @Param("example") ProductEslBindingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ProductEslBinding row, @Param("example") ProductEslBindingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductEslBinding row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ProductEslBinding row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductEslBinding row);
}