server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://192.168.10.50:3306/eslplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useInformationSchema=true&rewriteBatchedStatements=true
    username: panda
    password: panda@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 如果使用Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  rabbitmq:
    host: 192.168.10.50
    port: 5672
    username: panda
    password: panda@123
  mqtt:
    username: panda
    password: panda@123
    url: tcp://192.168.10.30:1883
    client:
      id: data_server_1
    default:
      topic: esl/server/data

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pandatech.downloadcf.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.pandatech.downloadcf.mapper: debug

# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true

# 应用配置
app:
  # 模板下载基础URL
  template:
    download:
      base-url: http://localhost:8080/api/templates
    # 前端渲染服务配置
    rendering:
      api:
        url: http://localhost:3001  # 修复：移除路径，只保留基础URL
        key: snowy-print-api-2024
        enabled: true
        timeout: 30000  # 30秒超时
        retry-count: 3  # 重试次数
    base-url: http://10.3.36.25:8999/api/res/templ/loadtemple
  esl:
    # 价签刷新配置
    refresh:
      # 默认租户ID
      default-tenant-id: "396a5189-53d8-4354-bcfa-27d57d9d69ad"
      # 默认门店编码
      default-store-code: "STORE001"
      # 强制刷新标志
      force-refresh: true
      # 默认模板ID（当价签没有绑定模板时使用）
      default-template-id: "default_template"
      # 校验码计算方式（md5, crc32等）
      checksum-algorithm: "md5"
    # 字段映射配置
    field-mapping:
      # 默认品牌编码
      default-brand-code: "DEFAULT"
      # 强制转换字段列表
      force-convert-fields:
        - "GOODS_NAME"
        - "GOODS_CODE"
    
    # 品牌配置
    brands:
      aes001:
        name: "攀攀科技"
        code: "AES001"
        enabled: true
        executor-type: MQTT
        template-format: CUSTOM
      yaliang001:
        name: "雅量科技"
        code: "YALIANG001"
        enabled: true
        executor-type: MQTT
        template-format: CUSTOM
        # 雅量品牌特定配置
        device-specs:
          - size: "2.13"
            width: 250
            height: 122
            color-mode: "BW"
            supported-formats: ["PNG", "BMP"]
          - size: "2.9"
            width: 296
            height: 128
            color-mode: "BW"
            supported-formats: ["PNG", "BMP"]
          - size: "4.2"
            width: 400
            height: 300
            color-mode: "BWR"
            supported-formats: ["PNG", "BMP"]
        mqtt:
          topic-prefix: "yaliang/esl"
          qos: 1
          retain: false
        image:
          max-size: 2097152  # 2MB
          compression-quality: 0.8
          supported-formats: ["PNG", "BMP"]
        validation:
          device-code-pattern: "^YL[0-9A-F]{8}$"
          mac-address-pattern: "^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
        
    # 缓存配置
    cache:
      enabled: true
      ttl: 300 # 5分钟
      max-size: 1000
      
    # 批处理配置
    batch:
      size: 100
      timeout: 30000 # 30秒
      
    # 重试配置
    retry:
      max-attempts: 3
      delay: 1000 # 1秒
      multiplier: 2.0
