server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eslplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useInformationSchema=true&rewriteBatchedStatements=true
    username: panda
    password: panda@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
  rabbitmq:
    host: 192.168.10.50
    port: 5672
    username: panda
    password: panda@123
    
  mqtt:
    username: panda
    password: panda@123
    url: tcp://47.119.183.105:1883
    client:
      id: data_server_1
    default:
      topic: esl/server/data

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pandatech.downloadcf.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.pandatech.downloadcf.mapper: debug

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: true

# 应用配置
app:
  # 模板下载配置
  template:
    base-url: http://10.3.36.25:8999/api/res/templ/loadtemple
    
  # ESL电子价签配置
  esl:
    # 价签刷新配置
    refresh:
      default-tenant-id: "396a5189-53d8-4354-bcfa-27d57d9d69ad"
      default-store-code: "STORE001"
      force-refresh: true
      default-template-id: "default_template"
      checksum-algorithm: "md5"
      
    # 字段映射配置
    field-mapping:
      default-brand-code: "DEFAULT"
      force-convert-fields:
        - "GOODS_NAME"
        - "GOODS_CODE"
    
    # 品牌配置
    brands:
      # 攀攀科技品牌配置
      aes001:
        name: "攀攀科技"
        code: "AES001"
        enabled: true
        executor-type: MQTT
        template-format: CUSTOM
        
      # 雅量科技品牌配置
      yaliang001:
        name: "雅量科技"
        code: "YALIANG001"
        enabled: true
        executor-type: "mqtt"
        template-format: "json"
        default-esl-id: "06000000195B"
        mqtt-topic-prefix: "yl-esl"
        default-device-type: 1
        default-refresh-action: 3
        default-refresh-area: 1
        
        # 设备规格配置
        device-specs:
          specs:
            "1.54":
              width: 200
              height: 200
              rotation: 90
              supported: true
            "1.54_old":
              width: 152
              height: 152
              rotation: 90
              supported: false
            "2.13":
              width: 250
              height: 122
              rotation: 90
              supported: true
            "2.13_old":
              width: 212
              height: 104
              rotation: 90
              supported: false
            "2.66":
              width: 296
              height: 152
              rotation: 90
              supported: true
            "2.66_old":
              width: 296
              height: 160
              rotation: 90
              supported: false
            "2.9":
              width: 296
              height: 128
              rotation: 90
              supported: true
            "3.5":
              width: 384
              height: 184
              rotation: 90
              supported: true
            "4.2":
              width: 400
              height: 300
              rotation: 0
              supported: true
            "5.83":
              width: 648
              height: 480
              rotation: 0
              supported: true
            "7.5":
              width: 800
              height: 480
              rotation: 0
              supported: true
            "7.5_old":
              width: 640
              height: 384
              rotation: 0
              supported: false
            "10.2":
              width: 960
              height: 640
              rotation: 0
              supported: true
          default-spec: "2.13"
          
        # 数据格式配置
        data-format:
          image-data-type: 1
          layer-end: true
          price-decimal-places: 2
          number-decimal-places: 2
          
        # 验证配置
        validation:
          device-code-pattern: "^[A-Z0-9]{8}$"
          mac-address-pattern: "^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
          esl-id-pattern: "^[A-Z0-9]+-[A-F0-9]{16}$"
        
    # 缓存配置
    cache:
      enabled: true
      ttl: 300  # 5分钟
      max-size: 1000
      
    # 批处理配置
    batch:
      size: 100
      timeout: 30000  # 30秒
      
    # 重试配置
    retry:
      max-attempts: 3
      delay: 1000  # 1秒
      multiplier: 2.0
