server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://10.3.36.25:3306/company?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useInformationSchema=true&rewriteBatchedStatements=true
    username: panda
    password: panda@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 如果使用Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  rabbitmq:
    host: 10.3.36.15
    port: 5672
    username: panda
    password: panda@123
  mqtt:
    username: panda
    password: panda@123
    url: tcp://10.3.36.25:1883
    client:
      id: data_server_1
    default:
      topic: esl/server/data

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pandatech.downloadcf.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.pandatech.downloadcf.mapper: debug

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: true

# 模板下载配置
app:
  template:
    base-url: http://localhost:8999/api/res/templ/loadtemple
