package com.pandatech.downloadcf.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   品牌字段映射表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table esl_brand_field_mapping
 */
public class EslBrandFieldMapping implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   租户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * Database Column Remarks:
     *   排序码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.SORT_CODE
     *
     * @mbg.generated
     */
    private Integer sortCode;

    /**
     * Database Column Remarks:
     *   删除标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.DELETE_FLAG
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.CREATE_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   创建用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.UPDATE_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   修改用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * Database Column Remarks:
     *   品牌编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.BRAND_CODE
     *
     * @mbg.generated
     */
    private String brandCode;

    /**
     * Database Column Remarks:
     *   模板字段名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.TEMPLATE_FIELD
     *
     * @mbg.generated
     */
    private String templateField;

    /**
     * Database Column Remarks:
     *   系统字段编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.FIELD_CODE
     *
     * @mbg.generated
     */
    private String fieldCode;

    /**
     * Database Column Remarks:
     *   格式化规则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.FORMAT_RULE
     *
     * @mbg.generated
     */
    private String formatRule;

    /**
     * Database Column Remarks:
     *   扩展信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esl_brand_field_mapping.EXT_JSON
     *
     * @mbg.generated
     */
    private String extJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.ID
     *
     * @return the value of esl_brand_field_mapping.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.ID
     *
     * @param id the value for esl_brand_field_mapping.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.TENANT_ID
     *
     * @return the value of esl_brand_field_mapping.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.TENANT_ID
     *
     * @param tenantId the value for esl_brand_field_mapping.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.SORT_CODE
     *
     * @return the value of esl_brand_field_mapping.SORT_CODE
     *
     * @mbg.generated
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.SORT_CODE
     *
     * @param sortCode the value for esl_brand_field_mapping.SORT_CODE
     *
     * @mbg.generated
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.DELETE_FLAG
     *
     * @return the value of esl_brand_field_mapping.DELETE_FLAG
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.DELETE_FLAG
     *
     * @param deleteFlag the value for esl_brand_field_mapping.DELETE_FLAG
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.CREATE_TIME
     *
     * @return the value of esl_brand_field_mapping.CREATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.CREATE_TIME
     *
     * @param createTime the value for esl_brand_field_mapping.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.CREATE_USER
     *
     * @return the value of esl_brand_field_mapping.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.CREATE_USER
     *
     * @param createUser the value for esl_brand_field_mapping.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.UPDATE_TIME
     *
     * @return the value of esl_brand_field_mapping.UPDATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.UPDATE_TIME
     *
     * @param updateTime the value for esl_brand_field_mapping.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.UPDATE_USER
     *
     * @return the value of esl_brand_field_mapping.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.UPDATE_USER
     *
     * @param updateUser the value for esl_brand_field_mapping.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.BRAND_CODE
     *
     * @return the value of esl_brand_field_mapping.BRAND_CODE
     *
     * @mbg.generated
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.BRAND_CODE
     *
     * @param brandCode the value for esl_brand_field_mapping.BRAND_CODE
     *
     * @mbg.generated
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode == null ? null : brandCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.TEMPLATE_FIELD
     *
     * @return the value of esl_brand_field_mapping.TEMPLATE_FIELD
     *
     * @mbg.generated
     */
    public String getTemplateField() {
        return templateField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.TEMPLATE_FIELD
     *
     * @param templateField the value for esl_brand_field_mapping.TEMPLATE_FIELD
     *
     * @mbg.generated
     */
    public void setTemplateField(String templateField) {
        this.templateField = templateField == null ? null : templateField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.FIELD_CODE
     *
     * @return the value of esl_brand_field_mapping.FIELD_CODE
     *
     * @mbg.generated
     */
    public String getFieldCode() {
        return fieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.FIELD_CODE
     *
     * @param fieldCode the value for esl_brand_field_mapping.FIELD_CODE
     *
     * @mbg.generated
     */
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode == null ? null : fieldCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.FORMAT_RULE
     *
     * @return the value of esl_brand_field_mapping.FORMAT_RULE
     *
     * @mbg.generated
     */
    public String getFormatRule() {
        return formatRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.FORMAT_RULE
     *
     * @param formatRule the value for esl_brand_field_mapping.FORMAT_RULE
     *
     * @mbg.generated
     */
    public void setFormatRule(String formatRule) {
        this.formatRule = formatRule == null ? null : formatRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esl_brand_field_mapping.EXT_JSON
     *
     * @return the value of esl_brand_field_mapping.EXT_JSON
     *
     * @mbg.generated
     */
    public String getExtJson() {
        return extJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esl_brand_field_mapping.EXT_JSON
     *
     * @param extJson the value for esl_brand_field_mapping.EXT_JSON
     *
     * @mbg.generated
     */
    public void setExtJson(String extJson) {
        this.extJson = extJson == null ? null : extJson.trim();
    }

    /**
     * 获取源字段名称（系统字段编码）
     * fieldCode 是系统字段编码，作为数据来源
     *
     * @return 源字段名称
     */
    public String getSourceField() {
        return this.fieldCode;
    }

    /**
     * 获取目标字段名称（模板字段名）
     * templateField 是模板字段名，作为映射目标
     *
     * @return 目标字段名称
     */
    public String getTargetField() {
        return this.templateField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", sortCode=").append(sortCode);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", brandCode=").append(brandCode);
        sb.append(", templateField=").append(templateField);
        sb.append(", fieldCode=").append(fieldCode);
        sb.append(", formatRule=").append(formatRule);
        sb.append(", extJson=").append(extJson);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EslBrandFieldMapping other = (EslBrandFieldMapping) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
            && (this.getSortCode() == null ? other.getSortCode() == null : this.getSortCode().equals(other.getSortCode()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getBrandCode() == null ? other.getBrandCode() == null : this.getBrandCode().equals(other.getBrandCode()))
            && (this.getTemplateField() == null ? other.getTemplateField() == null : this.getTemplateField().equals(other.getTemplateField()))
            && (this.getFieldCode() == null ? other.getFieldCode() == null : this.getFieldCode().equals(other.getFieldCode()))
            && (this.getFormatRule() == null ? other.getFormatRule() == null : this.getFormatRule().equals(other.getFormatRule()))
            && (this.getExtJson() == null ? other.getExtJson() == null : this.getExtJson().equals(other.getExtJson()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esl_brand_field_mapping
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getSortCode() == null) ? 0 : getSortCode().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getBrandCode() == null) ? 0 : getBrandCode().hashCode());
        result = prime * result + ((getTemplateField() == null) ? 0 : getTemplateField().hashCode());
        result = prime * result + ((getFieldCode() == null) ? 0 : getFieldCode().hashCode());
        result = prime * result + ((getFormatRule() == null) ? 0 : getFormatRule().hashCode());
        result = prime * result + ((getExtJson() == null) ? 0 : getExtJson().hashCode());
        return result;
    }
}