package com.pandatech.downloadcf.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table panda_product
 */
public class PandaProductWithBLOBs extends PandaProduct implements Serializable {
    /**
     * Database Column Remarks:
     *   扩展信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.EXT_JSON
     *
     * @mbg.generated
     */
    private String extJson;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_DESCRIPTION
     *
     * @mbg.generated
     */
    private String productDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.EXT_JSON
     *
     * @return the value of panda_product.EXT_JSON
     *
     * @mbg.generated
     */
    public String getExtJson() {
        return extJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.EXT_JSON
     *
     * @param extJson the value for panda_product.EXT_JSON
     *
     * @mbg.generated
     */
    public void setExtJson(String extJson) {
        this.extJson = extJson == null ? null : extJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_DESCRIPTION
     *
     * @return the value of panda_product.PRODUCT_DESCRIPTION
     *
     * @mbg.generated
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_DESCRIPTION
     *
     * @param productDescription the value for panda_product.PRODUCT_DESCRIPTION
     *
     * @mbg.generated
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", extJson=").append(extJson);
        sb.append(", productDescription=").append(productDescription);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PandaProductWithBLOBs other = (PandaProductWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getStoreCode() == null ? other.getStoreCode() == null : this.getStoreCode().equals(other.getStoreCode()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProductCategory() == null ? other.getProductCategory() == null : this.getProductCategory().equals(other.getProductCategory()))
            && (this.getProductSpecification() == null ? other.getProductSpecification() == null : this.getProductSpecification().equals(other.getProductSpecification()))
            && (this.getProductBrand() == null ? other.getProductBrand() == null : this.getProductBrand().equals(other.getProductBrand()))
            && (this.getProductCostPrice() == null ? other.getProductCostPrice() == null : this.getProductCostPrice().equals(other.getProductCostPrice()))
            && (this.getProductRetailPrice() == null ? other.getProductRetailPrice() == null : this.getProductRetailPrice().equals(other.getProductRetailPrice()))
            && (this.getProductMembershipPrice() == null ? other.getProductMembershipPrice() == null : this.getProductMembershipPrice().equals(other.getProductMembershipPrice()))
            && (this.getProductDiscountPrice() == null ? other.getProductDiscountPrice() == null : this.getProductDiscountPrice().equals(other.getProductDiscountPrice()))
            && (this.getProductDiscount() == null ? other.getProductDiscount() == null : this.getProductDiscount().equals(other.getProductDiscount()))
            && (this.getProductWholesalePrice() == null ? other.getProductWholesalePrice() == null : this.getProductWholesalePrice().equals(other.getProductWholesalePrice()))
            && (this.getProductMaterial() == null ? other.getProductMaterial() == null : this.getProductMaterial().equals(other.getProductMaterial()))
            && (this.getProductImage() == null ? other.getProductImage() == null : this.getProductImage().equals(other.getProductImage()))
            && (this.getProductOrigin() == null ? other.getProductOrigin() == null : this.getProductOrigin().equals(other.getProductOrigin()))
            && (this.getProductQrcode() == null ? other.getProductQrcode() == null : this.getProductQrcode().equals(other.getProductQrcode()))
            && (this.getProductBarcode() == null ? other.getProductBarcode() == null : this.getProductBarcode().equals(other.getProductBarcode()))
            && (this.getProductUnit() == null ? other.getProductUnit() == null : this.getProductUnit().equals(other.getProductUnit()))
            && (this.getProductWeight() == null ? other.getProductWeight() == null : this.getProductWeight().equals(other.getProductWeight()))
            && (this.getProductStatus() == null ? other.getProductStatus() == null : this.getProductStatus().equals(other.getProductStatus()))
            && (this.getProductStock() == null ? other.getProductStock() == null : this.getProductStock().equals(other.getProductStock()))
            && (this.getEslTemplateCode() == null ? other.getEslTemplateCode() == null : this.getEslTemplateCode().equals(other.getEslTemplateCode()))
            && (this.getExtJson() == null ? other.getExtJson() == null : this.getExtJson().equals(other.getExtJson()))
            && (this.getProductDescription() == null ? other.getProductDescription() == null : this.getProductDescription().equals(other.getProductDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getStoreCode() == null) ? 0 : getStoreCode().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProductCategory() == null) ? 0 : getProductCategory().hashCode());
        result = prime * result + ((getProductSpecification() == null) ? 0 : getProductSpecification().hashCode());
        result = prime * result + ((getProductBrand() == null) ? 0 : getProductBrand().hashCode());
        result = prime * result + ((getProductCostPrice() == null) ? 0 : getProductCostPrice().hashCode());
        result = prime * result + ((getProductRetailPrice() == null) ? 0 : getProductRetailPrice().hashCode());
        result = prime * result + ((getProductMembershipPrice() == null) ? 0 : getProductMembershipPrice().hashCode());
        result = prime * result + ((getProductDiscountPrice() == null) ? 0 : getProductDiscountPrice().hashCode());
        result = prime * result + ((getProductDiscount() == null) ? 0 : getProductDiscount().hashCode());
        result = prime * result + ((getProductWholesalePrice() == null) ? 0 : getProductWholesalePrice().hashCode());
        result = prime * result + ((getProductMaterial() == null) ? 0 : getProductMaterial().hashCode());
        result = prime * result + ((getProductImage() == null) ? 0 : getProductImage().hashCode());
        result = prime * result + ((getProductOrigin() == null) ? 0 : getProductOrigin().hashCode());
        result = prime * result + ((getProductQrcode() == null) ? 0 : getProductQrcode().hashCode());
        result = prime * result + ((getProductBarcode() == null) ? 0 : getProductBarcode().hashCode());
        result = prime * result + ((getProductUnit() == null) ? 0 : getProductUnit().hashCode());
        result = prime * result + ((getProductWeight() == null) ? 0 : getProductWeight().hashCode());
        result = prime * result + ((getProductStatus() == null) ? 0 : getProductStatus().hashCode());
        result = prime * result + ((getProductStock() == null) ? 0 : getProductStock().hashCode());
        result = prime * result + ((getEslTemplateCode() == null) ? 0 : getEslTemplateCode().hashCode());
        result = prime * result + ((getExtJson() == null) ? 0 : getExtJson().hashCode());
        result = prime * result + ((getProductDescription() == null) ? 0 : getProductDescription().hashCode());
        return result;
    }
}