package com.pandatech.downloadcf.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PandaEslCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public PandaEslCriteria() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("TENANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("TENANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("TENANT_ID =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("TENANT_ID <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("TENANT_ID >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("TENANT_ID >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("TENANT_ID <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("TENANT_ID <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("TENANT_ID like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("TENANT_ID not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("TENANT_ID in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("TENANT_ID not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("TENANT_ID between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("TENANT_ID not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andSortCodeIsNull() {
            addCriterion("SORT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSortCodeIsNotNull() {
            addCriterion("SORT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSortCodeEqualTo(Integer value) {
            addCriterion("SORT_CODE =", value, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeNotEqualTo(Integer value) {
            addCriterion("SORT_CODE <>", value, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeGreaterThan(Integer value) {
            addCriterion("SORT_CODE >", value, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT_CODE >=", value, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeLessThan(Integer value) {
            addCriterion("SORT_CODE <", value, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeLessThanOrEqualTo(Integer value) {
            addCriterion("SORT_CODE <=", value, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeIn(List<Integer> values) {
            addCriterion("SORT_CODE in", values, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeNotIn(List<Integer> values) {
            addCriterion("SORT_CODE not in", values, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeBetween(Integer value1, Integer value2) {
            addCriterion("SORT_CODE between", value1, value2, "sortCode");
            return (Criteria) this;
        }

        public Criteria andSortCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT_CODE not between", value1, value2, "sortCode");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(String value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLike(String value) {
            addCriterion("DELETE_FLAG like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotLike(String value) {
            addCriterion("DELETE_FLAG not like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andEslIdIsNull() {
            addCriterion("ESL_ID is null");
            return (Criteria) this;
        }

        public Criteria andEslIdIsNotNull() {
            addCriterion("ESL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEslIdEqualTo(String value) {
            addCriterion("ESL_ID =", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdNotEqualTo(String value) {
            addCriterion("ESL_ID <>", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdGreaterThan(String value) {
            addCriterion("ESL_ID >", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdGreaterThanOrEqualTo(String value) {
            addCriterion("ESL_ID >=", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdLessThan(String value) {
            addCriterion("ESL_ID <", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdLessThanOrEqualTo(String value) {
            addCriterion("ESL_ID <=", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdLike(String value) {
            addCriterion("ESL_ID like", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdNotLike(String value) {
            addCriterion("ESL_ID not like", value, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdIn(List<String> values) {
            addCriterion("ESL_ID in", values, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdNotIn(List<String> values) {
            addCriterion("ESL_ID not in", values, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdBetween(String value1, String value2) {
            addCriterion("ESL_ID between", value1, value2, "eslId");
            return (Criteria) this;
        }

        public Criteria andEslIdNotBetween(String value1, String value2) {
            addCriterion("ESL_ID not between", value1, value2, "eslId");
            return (Criteria) this;
        }

        public Criteria andStoreCodeIsNull() {
            addCriterion("STORE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andStoreCodeIsNotNull() {
            addCriterion("STORE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andStoreCodeEqualTo(String value) {
            addCriterion("STORE_CODE =", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotEqualTo(String value) {
            addCriterion("STORE_CODE <>", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeGreaterThan(String value) {
            addCriterion("STORE_CODE >", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_CODE >=", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeLessThan(String value) {
            addCriterion("STORE_CODE <", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeLessThanOrEqualTo(String value) {
            addCriterion("STORE_CODE <=", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeLike(String value) {
            addCriterion("STORE_CODE like", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotLike(String value) {
            addCriterion("STORE_CODE not like", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeIn(List<String> values) {
            addCriterion("STORE_CODE in", values, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotIn(List<String> values) {
            addCriterion("STORE_CODE not in", values, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeBetween(String value1, String value2) {
            addCriterion("STORE_CODE between", value1, value2, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotBetween(String value1, String value2) {
            addCriterion("STORE_CODE not between", value1, value2, "storeCode");
            return (Criteria) this;
        }

        public Criteria andApSnIsNull() {
            addCriterion("AP_SN is null");
            return (Criteria) this;
        }

        public Criteria andApSnIsNotNull() {
            addCriterion("AP_SN is not null");
            return (Criteria) this;
        }

        public Criteria andApSnEqualTo(String value) {
            addCriterion("AP_SN =", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnNotEqualTo(String value) {
            addCriterion("AP_SN <>", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnGreaterThan(String value) {
            addCriterion("AP_SN >", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnGreaterThanOrEqualTo(String value) {
            addCriterion("AP_SN >=", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnLessThan(String value) {
            addCriterion("AP_SN <", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnLessThanOrEqualTo(String value) {
            addCriterion("AP_SN <=", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnLike(String value) {
            addCriterion("AP_SN like", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnNotLike(String value) {
            addCriterion("AP_SN not like", value, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnIn(List<String> values) {
            addCriterion("AP_SN in", values, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnNotIn(List<String> values) {
            addCriterion("AP_SN not in", values, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnBetween(String value1, String value2) {
            addCriterion("AP_SN between", value1, value2, "apSn");
            return (Criteria) this;
        }

        public Criteria andApSnNotBetween(String value1, String value2) {
            addCriterion("AP_SN not between", value1, value2, "apSn");
            return (Criteria) this;
        }

        public Criteria andEslModelIsNull() {
            addCriterion("ESL_MODEL is null");
            return (Criteria) this;
        }

        public Criteria andEslModelIsNotNull() {
            addCriterion("ESL_MODEL is not null");
            return (Criteria) this;
        }

        public Criteria andEslModelEqualTo(String value) {
            addCriterion("ESL_MODEL =", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelNotEqualTo(String value) {
            addCriterion("ESL_MODEL <>", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelGreaterThan(String value) {
            addCriterion("ESL_MODEL >", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelGreaterThanOrEqualTo(String value) {
            addCriterion("ESL_MODEL >=", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelLessThan(String value) {
            addCriterion("ESL_MODEL <", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelLessThanOrEqualTo(String value) {
            addCriterion("ESL_MODEL <=", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelLike(String value) {
            addCriterion("ESL_MODEL like", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelNotLike(String value) {
            addCriterion("ESL_MODEL not like", value, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelIn(List<String> values) {
            addCriterion("ESL_MODEL in", values, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelNotIn(List<String> values) {
            addCriterion("ESL_MODEL not in", values, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelBetween(String value1, String value2) {
            addCriterion("ESL_MODEL between", value1, value2, "eslModel");
            return (Criteria) this;
        }

        public Criteria andEslModelNotBetween(String value1, String value2) {
            addCriterion("ESL_MODEL not between", value1, value2, "eslModel");
            return (Criteria) this;
        }

        public Criteria andBoundProductIsNull() {
            addCriterion("BOUND_PRODUCT is null");
            return (Criteria) this;
        }

        public Criteria andBoundProductIsNotNull() {
            addCriterion("BOUND_PRODUCT is not null");
            return (Criteria) this;
        }

        public Criteria andBoundProductEqualTo(String value) {
            addCriterion("BOUND_PRODUCT =", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductNotEqualTo(String value) {
            addCriterion("BOUND_PRODUCT <>", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductGreaterThan(String value) {
            addCriterion("BOUND_PRODUCT >", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductGreaterThanOrEqualTo(String value) {
            addCriterion("BOUND_PRODUCT >=", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductLessThan(String value) {
            addCriterion("BOUND_PRODUCT <", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductLessThanOrEqualTo(String value) {
            addCriterion("BOUND_PRODUCT <=", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductLike(String value) {
            addCriterion("BOUND_PRODUCT like", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductNotLike(String value) {
            addCriterion("BOUND_PRODUCT not like", value, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductIn(List<String> values) {
            addCriterion("BOUND_PRODUCT in", values, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductNotIn(List<String> values) {
            addCriterion("BOUND_PRODUCT not in", values, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductBetween(String value1, String value2) {
            addCriterion("BOUND_PRODUCT between", value1, value2, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBoundProductNotBetween(String value1, String value2) {
            addCriterion("BOUND_PRODUCT not between", value1, value2, "boundProduct");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelIsNull() {
            addCriterion("BATTERY_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelIsNotNull() {
            addCriterion("BATTERY_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelEqualTo(Float value) {
            addCriterion("BATTERY_LEVEL =", value, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelNotEqualTo(Float value) {
            addCriterion("BATTERY_LEVEL <>", value, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelGreaterThan(Float value) {
            addCriterion("BATTERY_LEVEL >", value, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelGreaterThanOrEqualTo(Float value) {
            addCriterion("BATTERY_LEVEL >=", value, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelLessThan(Float value) {
            addCriterion("BATTERY_LEVEL <", value, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelLessThanOrEqualTo(Float value) {
            addCriterion("BATTERY_LEVEL <=", value, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelIn(List<Float> values) {
            addCriterion("BATTERY_LEVEL in", values, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelNotIn(List<Float> values) {
            addCriterion("BATTERY_LEVEL not in", values, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelBetween(Float value1, Float value2) {
            addCriterion("BATTERY_LEVEL between", value1, value2, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andBatteryLevelNotBetween(Float value1, Float value2) {
            addCriterion("BATTERY_LEVEL not between", value1, value2, "batteryLevel");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNull() {
            addCriterion("TEMPERATURE is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNotNull() {
            addCriterion("TEMPERATURE is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureEqualTo(Float value) {
            addCriterion("TEMPERATURE =", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotEqualTo(Float value) {
            addCriterion("TEMPERATURE <>", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThan(Float value) {
            addCriterion("TEMPERATURE >", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThanOrEqualTo(Float value) {
            addCriterion("TEMPERATURE >=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThan(Float value) {
            addCriterion("TEMPERATURE <", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThanOrEqualTo(Float value) {
            addCriterion("TEMPERATURE <=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureIn(List<Float> values) {
            addCriterion("TEMPERATURE in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotIn(List<Float> values) {
            addCriterion("TEMPERATURE not in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureBetween(Float value1, Float value2) {
            addCriterion("TEMPERATURE between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotBetween(Float value1, Float value2) {
            addCriterion("TEMPERATURE not between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthIsNull() {
            addCriterion("SIGNAL_STRENGTH is null");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthIsNotNull() {
            addCriterion("SIGNAL_STRENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthEqualTo(Integer value) {
            addCriterion("SIGNAL_STRENGTH =", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthNotEqualTo(Integer value) {
            addCriterion("SIGNAL_STRENGTH <>", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthGreaterThan(Integer value) {
            addCriterion("SIGNAL_STRENGTH >", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIGNAL_STRENGTH >=", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthLessThan(Integer value) {
            addCriterion("SIGNAL_STRENGTH <", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthLessThanOrEqualTo(Integer value) {
            addCriterion("SIGNAL_STRENGTH <=", value, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthIn(List<Integer> values) {
            addCriterion("SIGNAL_STRENGTH in", values, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthNotIn(List<Integer> values) {
            addCriterion("SIGNAL_STRENGTH not in", values, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthBetween(Integer value1, Integer value2) {
            addCriterion("SIGNAL_STRENGTH between", value1, value2, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andSignalStrengthNotBetween(Integer value1, Integer value2) {
            addCriterion("SIGNAL_STRENGTH not between", value1, value2, "signalStrength");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountIsNull() {
            addCriterion("COMMUNICATION_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountIsNotNull() {
            addCriterion("COMMUNICATION_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountEqualTo(Integer value) {
            addCriterion("COMMUNICATION_COUNT =", value, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountNotEqualTo(Integer value) {
            addCriterion("COMMUNICATION_COUNT <>", value, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountGreaterThan(Integer value) {
            addCriterion("COMMUNICATION_COUNT >", value, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMUNICATION_COUNT >=", value, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountLessThan(Integer value) {
            addCriterion("COMMUNICATION_COUNT <", value, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountLessThanOrEqualTo(Integer value) {
            addCriterion("COMMUNICATION_COUNT <=", value, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountIn(List<Integer> values) {
            addCriterion("COMMUNICATION_COUNT in", values, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountNotIn(List<Integer> values) {
            addCriterion("COMMUNICATION_COUNT not in", values, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountBetween(Integer value1, Integer value2) {
            addCriterion("COMMUNICATION_COUNT between", value1, value2, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andCommunicationCountNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMUNICATION_COUNT not between", value1, value2, "communicationCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountIsNull() {
            addCriterion("FAILURE_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andFailureCountIsNotNull() {
            addCriterion("FAILURE_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFailureCountEqualTo(Integer value) {
            addCriterion("FAILURE_COUNT =", value, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountNotEqualTo(Integer value) {
            addCriterion("FAILURE_COUNT <>", value, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountGreaterThan(Integer value) {
            addCriterion("FAILURE_COUNT >", value, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("FAILURE_COUNT >=", value, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountLessThan(Integer value) {
            addCriterion("FAILURE_COUNT <", value, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountLessThanOrEqualTo(Integer value) {
            addCriterion("FAILURE_COUNT <=", value, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountIn(List<Integer> values) {
            addCriterion("FAILURE_COUNT in", values, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountNotIn(List<Integer> values) {
            addCriterion("FAILURE_COUNT not in", values, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountBetween(Integer value1, Integer value2) {
            addCriterion("FAILURE_COUNT between", value1, value2, "failureCount");
            return (Criteria) this;
        }

        public Criteria andFailureCountNotBetween(Integer value1, Integer value2) {
            addCriterion("FAILURE_COUNT not between", value1, value2, "failureCount");
            return (Criteria) this;
        }

        public Criteria andEslCategoryIsNull() {
            addCriterion("ESL_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andEslCategoryIsNotNull() {
            addCriterion("ESL_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andEslCategoryEqualTo(String value) {
            addCriterion("ESL_CATEGORY =", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryNotEqualTo(String value) {
            addCriterion("ESL_CATEGORY <>", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryGreaterThan(String value) {
            addCriterion("ESL_CATEGORY >", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("ESL_CATEGORY >=", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryLessThan(String value) {
            addCriterion("ESL_CATEGORY <", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryLessThanOrEqualTo(String value) {
            addCriterion("ESL_CATEGORY <=", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryLike(String value) {
            addCriterion("ESL_CATEGORY like", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryNotLike(String value) {
            addCriterion("ESL_CATEGORY not like", value, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryIn(List<String> values) {
            addCriterion("ESL_CATEGORY in", values, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryNotIn(List<String> values) {
            addCriterion("ESL_CATEGORY not in", values, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryBetween(String value1, String value2) {
            addCriterion("ESL_CATEGORY between", value1, value2, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslCategoryNotBetween(String value1, String value2) {
            addCriterion("ESL_CATEGORY not between", value1, value2, "eslCategory");
            return (Criteria) this;
        }

        public Criteria andEslStatusIsNull() {
            addCriterion("ESL_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andEslStatusIsNotNull() {
            addCriterion("ESL_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andEslStatusEqualTo(String value) {
            addCriterion("ESL_STATUS =", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusNotEqualTo(String value) {
            addCriterion("ESL_STATUS <>", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusGreaterThan(String value) {
            addCriterion("ESL_STATUS >", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ESL_STATUS >=", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusLessThan(String value) {
            addCriterion("ESL_STATUS <", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusLessThanOrEqualTo(String value) {
            addCriterion("ESL_STATUS <=", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusLike(String value) {
            addCriterion("ESL_STATUS like", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusNotLike(String value) {
            addCriterion("ESL_STATUS not like", value, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusIn(List<String> values) {
            addCriterion("ESL_STATUS in", values, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusNotIn(List<String> values) {
            addCriterion("ESL_STATUS not in", values, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusBetween(String value1, String value2) {
            addCriterion("ESL_STATUS between", value1, value2, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andEslStatusNotBetween(String value1, String value2) {
            addCriterion("ESL_STATUS not between", value1, value2, "eslStatus");
            return (Criteria) this;
        }

        public Criteria andScreenColorIsNull() {
            addCriterion("SCREEN_COLOR is null");
            return (Criteria) this;
        }

        public Criteria andScreenColorIsNotNull() {
            addCriterion("SCREEN_COLOR is not null");
            return (Criteria) this;
        }

        public Criteria andScreenColorEqualTo(String value) {
            addCriterion("SCREEN_COLOR =", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorNotEqualTo(String value) {
            addCriterion("SCREEN_COLOR <>", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorGreaterThan(String value) {
            addCriterion("SCREEN_COLOR >", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorGreaterThanOrEqualTo(String value) {
            addCriterion("SCREEN_COLOR >=", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorLessThan(String value) {
            addCriterion("SCREEN_COLOR <", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorLessThanOrEqualTo(String value) {
            addCriterion("SCREEN_COLOR <=", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorLike(String value) {
            addCriterion("SCREEN_COLOR like", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorNotLike(String value) {
            addCriterion("SCREEN_COLOR not like", value, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorIn(List<String> values) {
            addCriterion("SCREEN_COLOR in", values, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorNotIn(List<String> values) {
            addCriterion("SCREEN_COLOR not in", values, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorBetween(String value1, String value2) {
            addCriterion("SCREEN_COLOR between", value1, value2, "screenColor");
            return (Criteria) this;
        }

        public Criteria andScreenColorNotBetween(String value1, String value2) {
            addCriterion("SCREEN_COLOR not between", value1, value2, "screenColor");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodIsNull() {
            addCriterion("COMMUNICATION_METHOD is null");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodIsNotNull() {
            addCriterion("COMMUNICATION_METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodEqualTo(String value) {
            addCriterion("COMMUNICATION_METHOD =", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodNotEqualTo(String value) {
            addCriterion("COMMUNICATION_METHOD <>", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodGreaterThan(String value) {
            addCriterion("COMMUNICATION_METHOD >", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodGreaterThanOrEqualTo(String value) {
            addCriterion("COMMUNICATION_METHOD >=", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodLessThan(String value) {
            addCriterion("COMMUNICATION_METHOD <", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodLessThanOrEqualTo(String value) {
            addCriterion("COMMUNICATION_METHOD <=", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodLike(String value) {
            addCriterion("COMMUNICATION_METHOD like", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodNotLike(String value) {
            addCriterion("COMMUNICATION_METHOD not like", value, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodIn(List<String> values) {
            addCriterion("COMMUNICATION_METHOD in", values, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodNotIn(List<String> values) {
            addCriterion("COMMUNICATION_METHOD not in", values, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodBetween(String value1, String value2) {
            addCriterion("COMMUNICATION_METHOD between", value1, value2, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andCommunicationMethodNotBetween(String value1, String value2) {
            addCriterion("COMMUNICATION_METHOD not between", value1, value2, "communicationMethod");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andHardwareIsNull() {
            addCriterion("HARDWARE is null");
            return (Criteria) this;
        }

        public Criteria andHardwareIsNotNull() {
            addCriterion("HARDWARE is not null");
            return (Criteria) this;
        }

        public Criteria andHardwareEqualTo(String value) {
            addCriterion("HARDWARE =", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareNotEqualTo(String value) {
            addCriterion("HARDWARE <>", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareGreaterThan(String value) {
            addCriterion("HARDWARE >", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareGreaterThanOrEqualTo(String value) {
            addCriterion("HARDWARE >=", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareLessThan(String value) {
            addCriterion("HARDWARE <", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareLessThanOrEqualTo(String value) {
            addCriterion("HARDWARE <=", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareLike(String value) {
            addCriterion("HARDWARE like", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareNotLike(String value) {
            addCriterion("HARDWARE not like", value, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareIn(List<String> values) {
            addCriterion("HARDWARE in", values, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareNotIn(List<String> values) {
            addCriterion("HARDWARE not in", values, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareBetween(String value1, String value2) {
            addCriterion("HARDWARE between", value1, value2, "hardware");
            return (Criteria) this;
        }

        public Criteria andHardwareNotBetween(String value1, String value2) {
            addCriterion("HARDWARE not between", value1, value2, "hardware");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table panda_esl
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table panda_esl
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}