package com.pandatech.downloadcf.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table panda_product
 */
public class PandaProduct extends  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   租户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * Database Column Remarks:
     *   删除标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.DELETE_FLAG
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.CREATE_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   创建用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.UPDATE_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   修改用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * Database Column Remarks:
     *   商品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_ID
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   门店编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.STORE_CODE
     *
     * @mbg.generated
     */
    private String storeCode;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_NAME
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   商品分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_CATEGORY
     *
     * @mbg.generated
     */
    private String productCategory;

    /**
     * Database Column Remarks:
     *   商品规格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_SPECIFICATION
     *
     * @mbg.generated
     */
    private String productSpecification;

    /**
     * Database Column Remarks:
     *   商品品牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_BRAND
     *
     * @mbg.generated
     */
    private String productBrand;

    /**
     * Database Column Remarks:
     *   商品成本价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_COST_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal productCostPrice;

    /**
     * Database Column Remarks:
     *   商品零售价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_RETAIL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal productRetailPrice;

    /**
     * Database Column Remarks:
     *   商品会员价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_MEMBERSHIP_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal productMembershipPrice;

    /**
     * Database Column Remarks:
     *   商品折扣价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal productDiscountPrice;

    /**
     * Database Column Remarks:
     *   商品折扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_DISCOUNT
     *
     * @mbg.generated
     */
    private BigDecimal productDiscount;

    /**
     * Database Column Remarks:
     *   商品批发价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_WHOLESALE_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal productWholesalePrice;

    /**
     * Database Column Remarks:
     *   商品材质
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_MATERIAL
     *
     * @mbg.generated
     */
    private String productMaterial;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_IMAGE
     *
     * @mbg.generated
     */
    private String productImage;

    /**
     * Database Column Remarks:
     *   商品产地
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_ORIGIN
     *
     * @mbg.generated
     */
    private String productOrigin;

    /**
     * Database Column Remarks:
     *   二维码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_QRCODE
     *
     * @mbg.generated
     */
    private String productQrcode;

    /**
     * Database Column Remarks:
     *   条形码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_BARCODE
     *
     * @mbg.generated
     */
    private String productBarcode;

    /**
     * Database Column Remarks:
     *   商品单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_UNIT
     *
     * @mbg.generated
     */
    private String productUnit;

    /**
     * Database Column Remarks:
     *   产品重量（kg）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_WEIGHT
     *
     * @mbg.generated
     */
    private BigDecimal productWeight;

    /**
     * Database Column Remarks:
     *   商品状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_STATUS
     *
     * @mbg.generated
     */
    private String productStatus;

    /**
     * Database Column Remarks:
     *   商品库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.PRODUCT_STOCK
     *
     * @mbg.generated
     */
    private Integer productStock;

    /**
     * Database Column Remarks:
     *   电子价签模版
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panda_product.ESL_TEMPLATE_CODE
     *
     * @mbg.generated
     */
    private String eslTemplateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.ID
     *
     * @return the value of panda_product.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.ID
     *
     * @param id the value for panda_product.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.TENANT_ID
     *
     * @return the value of panda_product.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.TENANT_ID
     *
     * @param tenantId the value for panda_product.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.DELETE_FLAG
     *
     * @return the value of panda_product.DELETE_FLAG
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.DELETE_FLAG
     *
     * @param deleteFlag the value for panda_product.DELETE_FLAG
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.CREATE_TIME
     *
     * @return the value of panda_product.CREATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.CREATE_TIME
     *
     * @param createTime the value for panda_product.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.CREATE_USER
     *
     * @return the value of panda_product.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.CREATE_USER
     *
     * @param createUser the value for panda_product.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.UPDATE_TIME
     *
     * @return the value of panda_product.UPDATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.UPDATE_TIME
     *
     * @param updateTime the value for panda_product.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.UPDATE_USER
     *
     * @return the value of panda_product.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.UPDATE_USER
     *
     * @param updateUser the value for panda_product.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_ID
     *
     * @return the value of panda_product.PRODUCT_ID
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_ID
     *
     * @param productId the value for panda_product.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.STORE_CODE
     *
     * @return the value of panda_product.STORE_CODE
     *
     * @mbg.generated
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.STORE_CODE
     *
     * @param storeCode the value for panda_product.STORE_CODE
     *
     * @mbg.generated
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_NAME
     *
     * @return the value of panda_product.PRODUCT_NAME
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_NAME
     *
     * @param productName the value for panda_product.PRODUCT_NAME
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_CATEGORY
     *
     * @return the value of panda_product.PRODUCT_CATEGORY
     *
     * @mbg.generated
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_CATEGORY
     *
     * @param productCategory the value for panda_product.PRODUCT_CATEGORY
     *
     * @mbg.generated
     */
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory == null ? null : productCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_SPECIFICATION
     *
     * @return the value of panda_product.PRODUCT_SPECIFICATION
     *
     * @mbg.generated
     */
    public String getProductSpecification() {
        return productSpecification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_SPECIFICATION
     *
     * @param productSpecification the value for panda_product.PRODUCT_SPECIFICATION
     *
     * @mbg.generated
     */
    public void setProductSpecification(String productSpecification) {
        this.productSpecification = productSpecification == null ? null : productSpecification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_BRAND
     *
     * @return the value of panda_product.PRODUCT_BRAND
     *
     * @mbg.generated
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_BRAND
     *
     * @param productBrand the value for panda_product.PRODUCT_BRAND
     *
     * @mbg.generated
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand == null ? null : productBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_COST_PRICE
     *
     * @return the value of panda_product.PRODUCT_COST_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getProductCostPrice() {
        return productCostPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_COST_PRICE
     *
     * @param productCostPrice the value for panda_product.PRODUCT_COST_PRICE
     *
     * @mbg.generated
     */
    public void setProductCostPrice(BigDecimal productCostPrice) {
        this.productCostPrice = productCostPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_RETAIL_PRICE
     *
     * @return the value of panda_product.PRODUCT_RETAIL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getProductRetailPrice() {
        return productRetailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_RETAIL_PRICE
     *
     * @param productRetailPrice the value for panda_product.PRODUCT_RETAIL_PRICE
     *
     * @mbg.generated
     */
    public void setProductRetailPrice(BigDecimal productRetailPrice) {
        this.productRetailPrice = productRetailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_MEMBERSHIP_PRICE
     *
     * @return the value of panda_product.PRODUCT_MEMBERSHIP_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getProductMembershipPrice() {
        return productMembershipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_MEMBERSHIP_PRICE
     *
     * @param productMembershipPrice the value for panda_product.PRODUCT_MEMBERSHIP_PRICE
     *
     * @mbg.generated
     */
    public void setProductMembershipPrice(BigDecimal productMembershipPrice) {
        this.productMembershipPrice = productMembershipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_DISCOUNT_PRICE
     *
     * @return the value of panda_product.PRODUCT_DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getProductDiscountPrice() {
        return productDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_DISCOUNT_PRICE
     *
     * @param productDiscountPrice the value for panda_product.PRODUCT_DISCOUNT_PRICE
     *
     * @mbg.generated
     */
    public void setProductDiscountPrice(BigDecimal productDiscountPrice) {
        this.productDiscountPrice = productDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_DISCOUNT
     *
     * @return the value of panda_product.PRODUCT_DISCOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getProductDiscount() {
        return productDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_DISCOUNT
     *
     * @param productDiscount the value for panda_product.PRODUCT_DISCOUNT
     *
     * @mbg.generated
     */
    public void setProductDiscount(BigDecimal productDiscount) {
        this.productDiscount = productDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_WHOLESALE_PRICE
     *
     * @return the value of panda_product.PRODUCT_WHOLESALE_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getProductWholesalePrice() {
        return productWholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_WHOLESALE_PRICE
     *
     * @param productWholesalePrice the value for panda_product.PRODUCT_WHOLESALE_PRICE
     *
     * @mbg.generated
     */
    public void setProductWholesalePrice(BigDecimal productWholesalePrice) {
        this.productWholesalePrice = productWholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_MATERIAL
     *
     * @return the value of panda_product.PRODUCT_MATERIAL
     *
     * @mbg.generated
     */
    public String getProductMaterial() {
        return productMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_MATERIAL
     *
     * @param productMaterial the value for panda_product.PRODUCT_MATERIAL
     *
     * @mbg.generated
     */
    public void setProductMaterial(String productMaterial) {
        this.productMaterial = productMaterial == null ? null : productMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_IMAGE
     *
     * @return the value of panda_product.PRODUCT_IMAGE
     *
     * @mbg.generated
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_IMAGE
     *
     * @param productImage the value for panda_product.PRODUCT_IMAGE
     *
     * @mbg.generated
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_ORIGIN
     *
     * @return the value of panda_product.PRODUCT_ORIGIN
     *
     * @mbg.generated
     */
    public String getProductOrigin() {
        return productOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_ORIGIN
     *
     * @param productOrigin the value for panda_product.PRODUCT_ORIGIN
     *
     * @mbg.generated
     */
    public void setProductOrigin(String productOrigin) {
        this.productOrigin = productOrigin == null ? null : productOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_QRCODE
     *
     * @return the value of panda_product.PRODUCT_QRCODE
     *
     * @mbg.generated
     */
    public String getProductQrcode() {
        return productQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_QRCODE
     *
     * @param productQrcode the value for panda_product.PRODUCT_QRCODE
     *
     * @mbg.generated
     */
    public void setProductQrcode(String productQrcode) {
        this.productQrcode = productQrcode == null ? null : productQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_BARCODE
     *
     * @return the value of panda_product.PRODUCT_BARCODE
     *
     * @mbg.generated
     */
    public String getProductBarcode() {
        return productBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_BARCODE
     *
     * @param productBarcode the value for panda_product.PRODUCT_BARCODE
     *
     * @mbg.generated
     */
    public void setProductBarcode(String productBarcode) {
        this.productBarcode = productBarcode == null ? null : productBarcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_UNIT
     *
     * @return the value of panda_product.PRODUCT_UNIT
     *
     * @mbg.generated
     */
    public String getProductUnit() {
        return productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_UNIT
     *
     * @param productUnit the value for panda_product.PRODUCT_UNIT
     *
     * @mbg.generated
     */
    public void setProductUnit(String productUnit) {
        this.productUnit = productUnit == null ? null : productUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_WEIGHT
     *
     * @return the value of panda_product.PRODUCT_WEIGHT
     *
     * @mbg.generated
     */
    public BigDecimal getProductWeight() {
        return productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_WEIGHT
     *
     * @param productWeight the value for panda_product.PRODUCT_WEIGHT
     *
     * @mbg.generated
     */
    public void setProductWeight(BigDecimal productWeight) {
        this.productWeight = productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_STATUS
     *
     * @return the value of panda_product.PRODUCT_STATUS
     *
     * @mbg.generated
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_STATUS
     *
     * @param productStatus the value for panda_product.PRODUCT_STATUS
     *
     * @mbg.generated
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus == null ? null : productStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.PRODUCT_STOCK
     *
     * @return the value of panda_product.PRODUCT_STOCK
     *
     * @mbg.generated
     */
    public Integer getProductStock() {
        return productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.PRODUCT_STOCK
     *
     * @param productStock the value for panda_product.PRODUCT_STOCK
     *
     * @mbg.generated
     */
    public void setProductStock(Integer productStock) {
        this.productStock = productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panda_product.ESL_TEMPLATE_CODE
     *
     * @return the value of panda_product.ESL_TEMPLATE_CODE
     *
     * @mbg.generated
     */
    public String getEslTemplateCode() {
        return eslTemplateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panda_product.ESL_TEMPLATE_CODE
     *
     * @param eslTemplateCode the value for panda_product.ESL_TEMPLATE_CODE
     *
     * @mbg.generated
     */
    public void setEslTemplateCode(String eslTemplateCode) {
        this.eslTemplateCode = eslTemplateCode == null ? null : eslTemplateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", productId=").append(productId);
        sb.append(", storeCode=").append(storeCode);
        sb.append(", productName=").append(productName);
        sb.append(", productCategory=").append(productCategory);
        sb.append(", productSpecification=").append(productSpecification);
        sb.append(", productBrand=").append(productBrand);
        sb.append(", productCostPrice=").append(productCostPrice);
        sb.append(", productRetailPrice=").append(productRetailPrice);
        sb.append(", productMembershipPrice=").append(productMembershipPrice);
        sb.append(", productDiscountPrice=").append(productDiscountPrice);
        sb.append(", productDiscount=").append(productDiscount);
        sb.append(", productWholesalePrice=").append(productWholesalePrice);
        sb.append(", productMaterial=").append(productMaterial);
        sb.append(", productImage=").append(productImage);
        sb.append(", productOrigin=").append(productOrigin);
        sb.append(", productQrcode=").append(productQrcode);
        sb.append(", productBarcode=").append(productBarcode);
        sb.append(", productUnit=").append(productUnit);
        sb.append(", productWeight=").append(productWeight);
        sb.append(", productStatus=").append(productStatus);
        sb.append(", productStock=").append(productStock);
        sb.append(", eslTemplateCode=").append(eslTemplateCode);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PandaProduct other = (PandaProduct) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getStoreCode() == null ? other.getStoreCode() == null : this.getStoreCode().equals(other.getStoreCode()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProductCategory() == null ? other.getProductCategory() == null : this.getProductCategory().equals(other.getProductCategory()))
            && (this.getProductSpecification() == null ? other.getProductSpecification() == null : this.getProductSpecification().equals(other.getProductSpecification()))
            && (this.getProductBrand() == null ? other.getProductBrand() == null : this.getProductBrand().equals(other.getProductBrand()))
            && (this.getProductCostPrice() == null ? other.getProductCostPrice() == null : this.getProductCostPrice().equals(other.getProductCostPrice()))
            && (this.getProductRetailPrice() == null ? other.getProductRetailPrice() == null : this.getProductRetailPrice().equals(other.getProductRetailPrice()))
            && (this.getProductMembershipPrice() == null ? other.getProductMembershipPrice() == null : this.getProductMembershipPrice().equals(other.getProductMembershipPrice()))
            && (this.getProductDiscountPrice() == null ? other.getProductDiscountPrice() == null : this.getProductDiscountPrice().equals(other.getProductDiscountPrice()))
            && (this.getProductDiscount() == null ? other.getProductDiscount() == null : this.getProductDiscount().equals(other.getProductDiscount()))
            && (this.getProductWholesalePrice() == null ? other.getProductWholesalePrice() == null : this.getProductWholesalePrice().equals(other.getProductWholesalePrice()))
            && (this.getProductMaterial() == null ? other.getProductMaterial() == null : this.getProductMaterial().equals(other.getProductMaterial()))
            && (this.getProductImage() == null ? other.getProductImage() == null : this.getProductImage().equals(other.getProductImage()))
            && (this.getProductOrigin() == null ? other.getProductOrigin() == null : this.getProductOrigin().equals(other.getProductOrigin()))
            && (this.getProductQrcode() == null ? other.getProductQrcode() == null : this.getProductQrcode().equals(other.getProductQrcode()))
            && (this.getProductBarcode() == null ? other.getProductBarcode() == null : this.getProductBarcode().equals(other.getProductBarcode()))
            && (this.getProductUnit() == null ? other.getProductUnit() == null : this.getProductUnit().equals(other.getProductUnit()))
            && (this.getProductWeight() == null ? other.getProductWeight() == null : this.getProductWeight().equals(other.getProductWeight()))
            && (this.getProductStatus() == null ? other.getProductStatus() == null : this.getProductStatus().equals(other.getProductStatus()))
            && (this.getProductStock() == null ? other.getProductStock() == null : this.getProductStock().equals(other.getProductStock()))
            && (this.getEslTemplateCode() == null ? other.getEslTemplateCode() == null : this.getEslTemplateCode().equals(other.getEslTemplateCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panda_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getStoreCode() == null) ? 0 : getStoreCode().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProductCategory() == null) ? 0 : getProductCategory().hashCode());
        result = prime * result + ((getProductSpecification() == null) ? 0 : getProductSpecification().hashCode());
        result = prime * result + ((getProductBrand() == null) ? 0 : getProductBrand().hashCode());
        result = prime * result + ((getProductCostPrice() == null) ? 0 : getProductCostPrice().hashCode());
        result = prime * result + ((getProductRetailPrice() == null) ? 0 : getProductRetailPrice().hashCode());
        result = prime * result + ((getProductMembershipPrice() == null) ? 0 : getProductMembershipPrice().hashCode());
        result = prime * result + ((getProductDiscountPrice() == null) ? 0 : getProductDiscountPrice().hashCode());
        result = prime * result + ((getProductDiscount() == null) ? 0 : getProductDiscount().hashCode());
        result = prime * result + ((getProductWholesalePrice() == null) ? 0 : getProductWholesalePrice().hashCode());
        result = prime * result + ((getProductMaterial() == null) ? 0 : getProductMaterial().hashCode());
        result = prime * result + ((getProductImage() == null) ? 0 : getProductImage().hashCode());
        result = prime * result + ((getProductOrigin() == null) ? 0 : getProductOrigin().hashCode());
        result = prime * result + ((getProductQrcode() == null) ? 0 : getProductQrcode().hashCode());
        result = prime * result + ((getProductBarcode() == null) ? 0 : getProductBarcode().hashCode());
        result = prime * result + ((getProductUnit() == null) ? 0 : getProductUnit().hashCode());
        result = prime * result + ((getProductWeight() == null) ? 0 : getProductWeight().hashCode());
        result = prime * result + ((getProductStatus() == null) ? 0 : getProductStatus().hashCode());
        result = prime * result + ((getProductStock() == null) ? 0 : getProductStock().hashCode());
        result = prime * result + ((getEslTemplateCode() == null) ? 0 : getEslTemplateCode().hashCode());
        return result;
    }
}