package com.pandatech.downloadcf.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   商品-电子价签绑定关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_esl_binding
 */
public class ProductEslBinding extends  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   租户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * Database Column Remarks:
     *   排序码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.SORT_CODE
     *
     * @mbg.generated
     */
    private Integer sortCode;

    /**
     * Database Column Remarks:
     *   删除标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.DELETE_FLAG
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.CREATE_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   创建用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.UPDATE_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   修改用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * Database Column Remarks:
     *   电子价签ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.ESL_ID
     *
     * @mbg.generated
     */
    private String eslId;

    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.PRODUCT_ID
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   绑定状态(A=有效,I=无效)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.BIND_STATUS
     *
     * @mbg.generated
     */
    private String bindStatus;

    /**
     * Database Column Remarks:
     *   绑定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.BIND_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime bindTime;

    /**
     * Database Column Remarks:
     *   解绑时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.UNBIND_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime unbindTime;

    /**
     * Database Column Remarks:
     *   绑定类型(PERMANENT/TEMPORARY)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.BINDING_TYPE
     *
     * @mbg.generated
     */
    private String bindingType;

    /**
     * Database Column Remarks:
     *   临时绑定到期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.EXPIRY_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime expiryDate;

    /**
     * Database Column Remarks:
     *   扩展信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_esl_binding.EXT_JSON
     *
     * @mbg.generated
     */
    private String extJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.ID
     *
     * @return the value of product_esl_binding.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.ID
     *
     * @param id the value for product_esl_binding.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.TENANT_ID
     *
     * @return the value of product_esl_binding.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.TENANT_ID
     *
     * @param tenantId the value for product_esl_binding.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.SORT_CODE
     *
     * @return the value of product_esl_binding.SORT_CODE
     *
     * @mbg.generated
     */
    public Integer getSortCode() {
        return sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.SORT_CODE
     *
     * @param sortCode the value for product_esl_binding.SORT_CODE
     *
     * @mbg.generated
     */
    public void setSortCode(Integer sortCode) {
        this.sortCode = sortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.DELETE_FLAG
     *
     * @return the value of product_esl_binding.DELETE_FLAG
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.DELETE_FLAG
     *
     * @param deleteFlag the value for product_esl_binding.DELETE_FLAG
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.CREATE_TIME
     *
     * @return the value of product_esl_binding.CREATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.CREATE_TIME
     *
     * @param createTime the value for product_esl_binding.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.CREATE_USER
     *
     * @return the value of product_esl_binding.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.CREATE_USER
     *
     * @param createUser the value for product_esl_binding.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.UPDATE_TIME
     *
     * @return the value of product_esl_binding.UPDATE_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.UPDATE_TIME
     *
     * @param updateTime the value for product_esl_binding.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.UPDATE_USER
     *
     * @return the value of product_esl_binding.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.UPDATE_USER
     *
     * @param updateUser the value for product_esl_binding.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.ESL_ID
     *
     * @return the value of product_esl_binding.ESL_ID
     *
     * @mbg.generated
     */
    public String getEslId() {
        return eslId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.ESL_ID
     *
     * @param eslId the value for product_esl_binding.ESL_ID
     *
     * @mbg.generated
     */
    public void setEslId(String eslId) {
        this.eslId = eslId == null ? null : eslId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.PRODUCT_ID
     *
     * @return the value of product_esl_binding.PRODUCT_ID
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.PRODUCT_ID
     *
     * @param productId the value for product_esl_binding.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.BIND_STATUS
     *
     * @return the value of product_esl_binding.BIND_STATUS
     *
     * @mbg.generated
     */
    public String getBindStatus() {
        return bindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.BIND_STATUS
     *
     * @param bindStatus the value for product_esl_binding.BIND_STATUS
     *
     * @mbg.generated
     */
    public void setBindStatus(String bindStatus) {
        this.bindStatus = bindStatus == null ? null : bindStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.BIND_TIME
     *
     * @return the value of product_esl_binding.BIND_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.BIND_TIME
     *
     * @param bindTime the value for product_esl_binding.BIND_TIME
     *
     * @mbg.generated
     */
    public void setBindTime(LocalDateTime bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.UNBIND_TIME
     *
     * @return the value of product_esl_binding.UNBIND_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getUnbindTime() {
        return unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.UNBIND_TIME
     *
     * @param unbindTime the value for product_esl_binding.UNBIND_TIME
     *
     * @mbg.generated
     */
    public void setUnbindTime(LocalDateTime unbindTime) {
        this.unbindTime = unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.BINDING_TYPE
     *
     * @return the value of product_esl_binding.BINDING_TYPE
     *
     * @mbg.generated
     */
    public String getBindingType() {
        return bindingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.BINDING_TYPE
     *
     * @param bindingType the value for product_esl_binding.BINDING_TYPE
     *
     * @mbg.generated
     */
    public void setBindingType(String bindingType) {
        this.bindingType = bindingType == null ? null : bindingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.EXPIRY_DATE
     *
     * @return the value of product_esl_binding.EXPIRY_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.EXPIRY_DATE
     *
     * @param expiryDate the value for product_esl_binding.EXPIRY_DATE
     *
     * @mbg.generated
     */
    public void setExpiryDate(LocalDateTime expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_esl_binding.EXT_JSON
     *
     * @return the value of product_esl_binding.EXT_JSON
     *
     * @mbg.generated
     */
    public String getExtJson() {
        return extJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_esl_binding.EXT_JSON
     *
     * @param extJson the value for product_esl_binding.EXT_JSON
     *
     * @mbg.generated
     */
    public void setExtJson(String extJson) {
        this.extJson = extJson == null ? null : extJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", sortCode=").append(sortCode);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", eslId=").append(eslId);
        sb.append(", productId=").append(productId);
        sb.append(", bindStatus=").append(bindStatus);
        sb.append(", bindTime=").append(bindTime);
        sb.append(", unbindTime=").append(unbindTime);
        sb.append(", bindingType=").append(bindingType);
        sb.append(", expiryDate=").append(expiryDate);
        sb.append(", extJson=").append(extJson);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductEslBinding other = (ProductEslBinding) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
            && (this.getSortCode() == null ? other.getSortCode() == null : this.getSortCode().equals(other.getSortCode()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getEslId() == null ? other.getEslId() == null : this.getEslId().equals(other.getEslId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getBindStatus() == null ? other.getBindStatus() == null : this.getBindStatus().equals(other.getBindStatus()))
            && (this.getBindTime() == null ? other.getBindTime() == null : this.getBindTime().equals(other.getBindTime()))
            && (this.getUnbindTime() == null ? other.getUnbindTime() == null : this.getUnbindTime().equals(other.getUnbindTime()))
            && (this.getBindingType() == null ? other.getBindingType() == null : this.getBindingType().equals(other.getBindingType()))
            && (this.getExpiryDate() == null ? other.getExpiryDate() == null : this.getExpiryDate().equals(other.getExpiryDate()))
            && (this.getExtJson() == null ? other.getExtJson() == null : this.getExtJson().equals(other.getExtJson()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_esl_binding
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getSortCode() == null) ? 0 : getSortCode().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getEslId() == null) ? 0 : getEslId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getBindStatus() == null) ? 0 : getBindStatus().hashCode());
        result = prime * result + ((getBindTime() == null) ? 0 : getBindTime().hashCode());
        result = prime * result + ((getUnbindTime() == null) ? 0 : getUnbindTime().hashCode());
        result = prime * result + ((getBindingType() == null) ? 0 : getBindingType().hashCode());
        result = prime * result + ((getExpiryDate() == null) ? 0 : getExpiryDate().hashCode());
        result = prime * result + ((getExtJson() == null) ? 0 : getExtJson().hashCode());
        return result;
    }
}